### ISSUE TITLE
Why not use thiserror crate?

### ISSUE THREAD

**Issue by tcharding** [Kixunil/bip21#2]
Is there some technical reason why bip21 does not use [thiserror](https://crates.io/crates/thiserror)? If the docs for `thiserror` are correct then the derived code should be the same (I have not looked at the generated code myself though).

> Thiserror deliberately does not appear in your public API. You get the same thing as if you had written an implementation of std::error::Error by hand, and switching from handwritten impls to thiserror or vice versa is not a breaking change.

I'm interested to understand you reasoning.

Thanks

**Comment by tcharding** [comment]
I think I answered my own question, is it because `bip21` defaults to being `no_std` and the implementation of `std::errro::Error` is feature gated?

**Comment by Kixunil** [comment]
As much as I love `thiserror` I really don't like to blow up the compile times by using proc macros in crates that don't need them that much. Manual impl of `std::error::Error` is not that bad (at least compared to `serde`, LOL).

Also there doesn't seem to be a way to **document** that the impl requires `std`.

We can revisit when the situation changes.

**Comment by tcharding** [comment]
If you feel like answering when are proc macros, in your opinion, worth the compile time and when are they not?

**Comment by Kixunil** [comment]
Sure, IMO they are worth compile time if the impls are huge and complicated - e.g. `serde` impls are a great example. (This can not be expressed with words - try yourself and you'll see!)
If the impls are like ~5 lines of code it's not worth it. (Also decreased attack surface is nice.)

If there's already another proc macro then adding another is not a big deal because they will share compile time for common stuff - mainly `syn`, `quote` and `proc_macro2`. E.g. if you already use `serde_derive` then adding `thiserror` is good.

**Comment by tcharding** [comment]
Are these included in 'if there is already another proc macro'?
```
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
```
Because its likely we will always have at least one of those? Or am I missing something?

**Comment by Kixunil** [comment]
Those come from the compiler, not external library. :)

**Comment by tcharding** [comment]
They come from the stand library not the compiler, right? Is there a the compile time difference between using proc macros from std as opposed to proc macros from other libraries?

**Comment by Kixunil** [comment]
TBH, I don't know. It was in the compiler in the past but maybe it was rewritten since then?

> Is there a the compile time difference between using proc macros from std as opposed to proc macros from other libraries?

Compiling proc macros takes 0 seconds because they are pre-compiled. For other libraries they must be compiled for every project and recompiled for every version update.
